### ISSUE TITLE
Compiling with Visual Studio

### ISSUE THREAD

**Issue by fred26** [jstaursky/hutch#1]
I managed to create a Solution but there are symbols and functions missing.

`Gravidade Código Descrição Projeto Arquivo Linha Estado de Supressão
Erro C2065 'CPUI_INSERT': identificador não declarado Decompile D:\Users\feder\Files\Code\Development\Ghidra Decompiler\Decompiler\dynamic.cc 58
Erro C2065 'CPUI_EXTRACT': identificador não declarado Decompile D:\Users\feder\Files\Code\Development\Ghidra Decompiler\Decompiler\dynamic.cc 58
Erro C2065 'CPUI_POPCOUNT': identificador não declarado Decompile D:\Users\feder\Files\Code\Development\Ghidra Decompiler\Decompiler\dynamic.cc 58
Gravidade Código Descrição Projeto Arquivo Linha Estado de Supressão
Erro C3861 'popcount': identificador não encontrado Decompile D:\Users\feder\Files\Code\Development\Ghidra Decompiler\Decompiler\ruleaction.cc 8500`

These enums and functions seem no to be shipped with the hutch source files. I have not updated to the new ghidra compiler source as it was mentioned that there is no 1-1 sync with it. Any hints?

Thanks

**Comment by fred26** [comment]
Managed to port it

**Comment by jstaursky** [comment]
Sorry I am just now seeing this. I actually do not use visual studio. However the build should work if you use [MSYS2](https://www.msys2.org/). Even if you do get visual studio to work for the sleigh compiler, you will likely run into issues with one of the examples as it uses `popen` along with `xxd` which I am not sure is available with visual studio (MSYS2 should work though)

**Comment by fred26** [comment]
Thanks. I managed to compile the sleigh part of the code wtih VS, but switching to c++17 in Visual Studio is incompatible with many of the hutch.cpp parts of the code. Any hints are appreciated. Thanks

**Comment by jstaursky** [comment]
sure thing, what kind of errors are you seeing?

Is it just the missing symbol definitions?

**Comment by jstaursky** [comment]
TBH you might have more fun using the python api, it has a less cumbersome api and more you can do with. If you are just trying to avoid starting up the ghidra GUI you could run it headless with something like 
```sh
#!/usr/bin/env bash

# use: ./run_headless -b <binary>
GHIDRA_PATH="$HOME/ghidra_9.2.2"
SCRIPT_DIR=pwd

set -x

while getopts 'b:' arg;
do
    case $arg in
        b)
            BINARY_NAME=`pwd`/"$OPTARG";
    esac
done
shift $(($OPTIND-1))

$GHIDRA_PATH/support/analyzeHeadless /tmp tmp-project \
            -import $BINARY_NAME -scriptPath $SCRIPT_DIR \
            -postScript experiment.py -deleteProject
```

But w/ the appropriate windows BAT file equivalences.
where `experiment.py` is the python2 script you would write.
