### ISSUE TITLE
Want to Help with Update

### ISSUE THREAD

**Issue by larkwiot** [jstaursky/hutch#2]
Hello,

I have recently been trying to integrate this project into my own since I need SLEIGH without the rest of Ghidra. An update to Hutch is very exciting! If there's any chance you'd like help with the update, please let me know!

**Comment by jstaursky** [comment]
Okay great! sorry just now seeing this. Been a bit hectic with work lately that I have not gotten as far along as I had hoped by now. But maybe let me know what features you are most interested in? Currently working on/looking into moving to an autotools build script and adding a pkg-config file with it.

**Comment by larkwiot** [comment]
Message me on Twitter with your preferred method of communication--I don't think GitHub issues are an efficent way to coordinate this kind of thing.

**Comment by jstaursky** [comment]
I agree, however i dont really know anything about twitter (nothing setup/no account there) but if you just want to send messages to my email or setup a discussion tab/section on github we can do that. Ill start checking this email more often. That is jstaursky at gmail.com
